"""Add is_accepted field

Revision ID: 82fba692b076
Revises: 6cb4a29c4e51
Create Date: 2025-06-24 14:31:09.783206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82fba692b076'
down_revision = '6cb4a29c4e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accepted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('is_accepted')

    # ### end Alembic commands ###
